export const fishCategories = [
  "Freshwater Fish",
  "Saltwater Fish",
  "Tropical Fish",
  "Cold Water Fish",
  "Game Fish",
  "Aquarium Fish",
  "Commercial Fish",
  "Endangered Fish",
  "Cichlids",
  "Tetras",
  "Gouramis",
  "Catfish",
  "Livebearers",
  "Barbs",
  "Rainbowfish",
  "Killifish",
  "Pufferfish",
  "Sturgeon",
  "Reef Fish",
  "Pelagic Fish",
  "Bottom Dwellers",
  "Sharks & Rays",
  "Eels",
  "Groupers",
  "Snappers",
  "Tuna",
  "Marlin",
  "Seahorses",
  "Angelfish",
  "Bettas",
  "Discus",
  "Guppies",
  "Mollies",
  "Platies",
  "Swordtails",
  "Rasboras",
  "Loaches",
  "Plecos",
  "Goldfish",
  "Koi",
  "Trout",
  "Salmon",
  "Whitefish",
  "Sticklebacks",
  "Bitterling",
  "African Cichlids",
  "South American Cichlids",
  "Dwarf Cichlids",
  "Oscars",
  "Clownfish",
  "Tangs",
  "Butterflyfish",
  "Angelfish (Marine)",
  "Wrasses",
  "Bass",
  "Trout (Game)",
  "Salmon (Game)",
  "Pike",
  "Tarpon",
  "Bonefish"
]